### ISSUE TITLE
How to use rpm module from pyenv for python 2.6.6 in Ubuntu14.04

### ISSUE THREAD

**Issue by jiafanzhou** [yyuu/pyenv#325]
On ubuntu 14.04, default python is 2.7.6. Also Installed pyenv for python 2.6.6.

In python 2.7.6, I can import rpm module, like below:
```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpm
>>> rpm.__file__
'/usr/lib/python2.7/dist-packages/rpm/__init__.pyc'

$ ll /usr/lib/python2.7/dist-packages/rpm
total 144
-rw-r--r-- 1 root root  5117 Jan 16 17:24 transaction.py
-rw-r--r-- 1 root root  2018 Jan 16 17:24 __init__.py
-rw-r--r-- 1 root root  6272 Jan 16 17:24 _rpmsmodule.so
-rw-r--r-- 1 root root 96544 Jan 16 17:24 _rpmmodule.so
-rw-r--r-- 1 root root 15888 Jan 16 17:24 _rpmbmodule.so
-rw-r--r-- 1 root root  5885 Jan 20 07:36 transaction.pyc
-rw-r--r-- 1 root root  2788 Jan 20 07:36 __init__.pyc

$ dpkg --get-selections | grep -i rpm
librpm3                                         install
librpmbuild3                                    install
librpmio3                                       install
librpmsign1                                     install
python-renderpm                                 install
python-rpm                                      install
rpm                                             install
rpm-common                                      install
rpm2cpio                                        install
```

I believe that rpm is the native C library.

However, in pyenv python version 2.6.6, I am not able to import rpm module:

```
$ pyenv activate py2.6.6 
(py2.6.6)ejiafzh@elx1411ctr-tr:~$ python
Python 2.6.6 (r266:84292, Nov 14 2014, 11:03:50) 
[GCC 4.8.2] on linux3
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named rpm
```

I tried to manually copy/paste all the .so file into pyenv 2.6.6 dist-package dir,
```
$ sudo cp -r /usr/lib/python2.7/dist-packages/rpm ~/.pyenv/versions/py2.6.6/lib/python2.6/site-packages
```

However, it ends with the following error:
```
$ python
Python 2.6.6 (r266:84292, Nov 14 2014, 11:03:50) 
[GCC 4.8.2] on linux3
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ejiafzh/.pyenv/versions/py2.6.6/lib/python2.6/site-packages/rpm/__init__.py", line 9, in <module>
    from rpm._rpm import *
ImportError: /home/ejiafzh/.pyenv/versions/py2.6.6/lib/python2.6/site-packages/rpm/_rpmmodule.so: undefined symbol: PyCapsule_Type
```
Any help?

**Comment by jiafanzhou** [comment]
Is this problem unique to me?

**Comment by jhermann** [comment]
Just pulling this from my crystal ball, but do you have "librpm-dev" installed?

**Comment by yyuu** [comment]
The `.so` is shared object, not a script file. Just copying it into custom build Python won't work. You'd need to build that package with pyenv-built python.

**Comment by jiafanzhou** [comment]
Any idea how to use the pyenv-built to build the rpm package?

**Comment by yyuu** [comment]
If you're not sure how you can deal with it, it'd be better to create a
virtualenv from system python with supplying '--system-site-package' might
be the easiest way to achieve.

-- 
山下 優 (やました ゆう)
peek824545201@gmail.com

**Comment by jiafanzhou** [comment]
Sorry, but my system python is 2.7.6, I am trying to use 2.6.6
