### ISSUE TITLE
Installing 2.6.6 fails - certificate issue downloading setuptools

### ISSUE THREAD

**Issue by cnk** [yyuu/pyenv#334]
Installing python 2.6.6 on RHEL 5.11 seems to go well until trying to download setuptools. It looks like wget doesn't like the Subject Alternate Name certificate that www.python.org / pypi.python.org uses. I see the --download-base option for ez_setup.py but I am not clear how that gets called from my 'pyenv install 2.6.6' command. What is the appropriate way to fix this?

running install_scripts
copying build/scripts-2.6/pydoc -> /home/cnk/.pyenv/versions/2.6.6/bin
copying build/scripts-2.6/idle -> /home/cnk/.pyenv/versions/2.6.6/bin
copying build/scripts-2.6/smtpd.py -> /home/cnk/.pyenv/versions/2.6.6/bin
copying build/scripts-2.6/2to3 -> /home/cnk/.pyenv/versions/2.6.6/bin
changing mode of /home/cnk/.pyenv/versions/2.6.6/bin/pydoc to 775
changing mode of /home/cnk/.pyenv/versions/2.6.6/bin/idle to 775
changing mode of /home/cnk/.pyenv/versions/2.6.6/bin/smtpd.py to 775
changing mode of /home/cnk/.pyenv/versions/2.6.6/bin/2to3 to 775
running install_egg_info
Writing /home/cnk/.pyenv/versions/2.6.6/lib/python2.6/lib-dynload/Python-2.6.6-py2.6.egg-info
if test -f /home/cnk/.pyenv/versions/2.6.6/bin/python -o -h /home/cnk/.pyenv/versions/2.6.6/bin/python; \
        then rm -f /home/cnk/.pyenv/versions/2.6.6/bin/python; \
        else true; \
        fi
(cd /home/cnk/.pyenv/versions/2.6.6/bin; ln python2.6 python)
rm -f /home/cnk/.pyenv/versions/2.6.6/bin/python-config
(cd /home/cnk/.pyenv/versions/2.6.6/bin; ln -s python2.6-config python-config)
Creating directory /home/cnk/.pyenv/versions/2.6.6/share/man
Creating directory /home/cnk/.pyenv/versions/2.6.6/share/man/man1
/usr/bin/install -c -m 644 ./Misc/python.man \
                /home/cnk/.pyenv/versions/2.6.6/share/man/man1/python.1
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-14.3.zip
Traceback (most recent call last):
  File "/tmp/python-build.20150317225553.3986/ez_setup.py", line 391, in <module>
    sys.exit(main())
  File "/tmp/python-build.20150317225553.3986/ez_setup.py", line 387, in main
    archive = download_setuptools(**_download_args(options))
  File "/tmp/python-build.20150317225553.3986/ez_setup.py", line 332, in download_setuptools
    downloader(url, saveto)
  File "/tmp/python-build.20150317225553.3986/ez_setup.py", line 268, in download_file_wget
    _clean_check(cmd, target)
  File "/tmp/python-build.20150317225553.3986/ez_setup.py", line 207, in _clean_check
    subprocess.check_call(cmd)
  File "/home/cnk/.pyenv/versions/2.6.6/lib/python2.6/subprocess.py", line 488, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-14.3.zip', '--quiet', '--output-document', '/tmp/python-build.20150317225553.3986/Python-2.6.6/setuptools-14.3.zip']' returned non-zero exit status 1

**Comment by cnk** [comment]
OK this is because the version of wget on RHEL5 is as old as dirt. After installing wget 1.16 from source, pyenv / pybuild builds pythons just fine.

For anyone else using RHEL 5, download latest wget from https://www.gnu.org/software/wget/, untar and do: 

./configure --with-ssl=openssl
make
sudo make install  # This will put wget in to /usr/local/bin/
