### ISSUE TITLE
pip install fails when installing 3.1.5

### ISSUE THREAD

**Issue by ju2wheels** [yyuu/pyenv#374]
Hi, im running Ubuntu 12.04 and attempting to install `3.1.5` with pyenv and get the following error:

```
Downloading Python-3.1.5.tgz...
-> http://python.org/ftp/python/3.1.5/Python-3.1.5.tgz
Installing Python-3.1.5...
patching file ./Modules/readline.c
Hunk #1 succeeded at 178 (offset -53 lines).
Hunk #2 succeeded at 692 (offset -81 lines).
Hunk #3 succeeded at 744 (offset -82 lines).
Hunk #4 succeeded at 801 (offset -83 lines).
Hunk #5 succeeded at 841 with fuzz 2 (offset -102 lines).
Installing setuptools from https://bootstrap.pypa.io/ez_setup.py...
Installing pip from https://bootstrap.pypa.io/get-pip.py...
error: failed to install pip via get-pip.py

BUILD FAILED (Ubuntu 12.04 using python-build 20150326-493-ge285f2e)

Inspect or clean up the working tree at /tmp/python-build.20150510212845.5111
Results logged to /tmp/python-build.20150510212845.5111.log

Last 10 log lines:
    main()
  File "/tmp/python-build.20150510212845.5111/get-pip.py", line 152, in main
    bootstrap(tmpdir=tmpdir)
  File "/tmp/python-build.20150510212845.5111/get-pip.py", line 130, in bootstrap
    sys.exit(pip.main(["install", "--upgrade"] + packages + args))
  File "/tmp/tmpUXKeIn/pip.zip/pip/__init__.py", line 217, in main
  File "/tmp/tmpUXKeIn/pip.zip/pip/basecommand.py", line 197, in main
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 565, in dictConfig
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 348, in configure
NameError: global name 'StandardError' is not defined
```

The end of the log contains this:

```
creating dist
creating 'dist/setuptools-15.2-py3.1.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing setuptools-15.2-py3.1.egg
Copying setuptools-15.2-py3.1.egg to /home/jalajara/.pyenv/versions/3.1.5/lib/python3.1/site-packages
Adding setuptools 15.2 to easy-install.pth file
Installing easy_install script to /home/jalajara/.pyenv/versions/3.1.5/bin
Installing easy_install-3.1 script to /home/jalajara/.pyenv/versions/3.1.5/bin

Installed /home/jalajara/.pyenv/versions/3.1.5/lib/python3.1/site-packages/setuptools-15.2-py3.1.egg
Processing dependencies for setuptools==15.2
Finished processing dependencies for setuptools==15.2
  File "build/bdist.linux-x86_64/egg/setuptools/tests/script-with-bom.py", line 1
    <U+FEFF># -*- coding: utf-8 -*-
      ^
SyntaxError: invalid character in identifier

Traceback (most recent call last):
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 347, in configure
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 454, in configure_filter
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 264, in configure_custom
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/python-build.20150510212845.5111/get-pip.py", line 17853, in <module>
    main()
  File "/tmp/python-build.20150510212845.5111/get-pip.py", line 152, in main
    bootstrap(tmpdir=tmpdir)
  File "/tmp/python-build.20150510212845.5111/get-pip.py", line 130, in bootstrap
    sys.exit(pip.main(["install", "--upgrade"] + packages + args))
  File "/tmp/tmpUXKeIn/pip.zip/pip/__init__.py", line 217, in main
  File "/tmp/tmpUXKeIn/pip.zip/pip/basecommand.py", line 197, in main
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 565, in dictConfig
  File "/tmp/tmpUXKeIn/pip.zip/pip/compat/dictconfig.py", line 348, in configure
NameError: global name 'StandardError' is not defined
```

**Comment by yyuu** [comment]
It would be a problem in get-pip.py itself.

**Comment by erickwilder** [comment]
I'm having the same problem on MacOSX. Any thoughts on how to solve it?

**Comment by RyanMagnusson** [comment]
I am also getting the error trying to install version 3.1.5 on Ubuntu 14.04

I have submitted a [pull request](https://github.com/pypa/pip/pull/2955) but not sure how popular that might be since [3.1.5 isn't officially supported](https://pip.pypa.io/en/stable/installing.html#python-os-support) by pip. 

Should the python-build install for 3.1.5 be passing 'ensurepip'?

**Comment by yyuu** [comment]
If there's some specific pip version which is working well with 3.1.x, we can fix the install definition to install that version of pip.

**Comment by joshkel** [comment]
Based on [this comment](https://github.com/pypa/pip/issues/2954#issuecomment-118223727), it sounds like pip simply doesn't support 3.1.x and doesn't care that it doesn't support 3.1.x.

**Comment by yyuu** [comment]
I forgot to mention this ticket in the commit comment but I changed to use older pip 1.5.6 for the definition of 3.1.5. Rebuilding 3.1.5 with pyenv would work.

https://github.com/yyuu/pyenv/commit/294738842c12c3ba118641326ec15f1d6a47aa23

**Comment by joshkel** [comment]
Thank you.

**Comment by RyanMagnusson** [comment]
Yes thank you.

**Comment by Ivoz** [comment]
pip 1.5.6 -> 6.0 dropped support for python 3.1.
