### ISSUE TITLE
OSX installation fails on importing _scproxy

### ISSUE THREAD

**Issue by oplatek** [yyuu/pyenv#521]
Hi,

I succesfully install pyenv via ``brew install pyenv `` but when I ran ``pyenv install 3.5.1`` it fails with ``ImportError: No module named '_scproxy'`` error.
I am running OSX 10.11.2 system Python 2.7.10

The last interesting lines from running pyenv log:

```sh
if test "x" != "x" ; then \
		rm -f /Users/oplatek/.pyenv/versions/3.5.1/bin/python3-32; \
		(cd /Users/oplatek/.pyenv/versions/3.5.1/bin; ln -s python3.5-32 python3-32) \
	fi
rm -f /Users/oplatek/.pyenv/versions/3.5.1/share/man/man1/python3.1
(cd /Users/oplatek/.pyenv/versions/3.5.1/share/man/man1; ln -s python3.5.1 python3.1)
if test "xupgrade" != "xno"  ; then \
		case upgrade in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Traceback (most recent call last):
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/ensurepip/__init__.py", line 209, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/ensurepip/__init__.py", line 116, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/ensurepip/__init__.py", line 40, in _run_pip
    import pip
  File "/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/tmpi06e_xqt/pip-7.1.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/tmpi06e_xqt/pip-7.1.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 10, in <module>
  File "/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/tmpi06e_xqt/pip-7.1.2-py2.py3-none-any.whl/pip/download.py", line 38, in <module>
  File "/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/tmpi06e_xqt/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 58, in <module>
  File "/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/tmpi06e_xqt/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 26, in <module>
  File "/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/tmpi06e_xqt/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/requests/compat.py", line 52, in <module>
  File "/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160109212517.60990/Python-3.5.1/Lib/urllib/request.py", line 2483, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ImportError: No module named '_scproxy'
make: *** [install] Error 1
```

Thank you for your help

**Comment by oplatek** [comment]
I found out that the ``_scproxy`` module was not compiled successfully: 
```sh
./python.exe -E ./setup.py install \
                --prefix=/Users/oplatek/.pyenv/versions/3.5.1 \
                --install-scripts=/Users/oplatek/.pyenv/versions/3.5.1/bin \
                --install-platlib=/Users/oplatek/.pyenv/versions/3.5.1/lib/python3.5/lib-dynload \
                --root=/
running install
running build
running build_ext
building '_scproxy' extension
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/oplatek/.pyenv/versions/3.5.1/include -I./Include -I. -IInclude -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/oplatek/.pyenv/versions/3.5.1/include -I/usr/local/include -I/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Inc
lude -I/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1 -c /private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.c -o build/temp.macosx-10.11-x86_64-3.5/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.o
In file included from /private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.c:6:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:124:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:60:
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:985:49: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationUI
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:987:54: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationContext
                                                     ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:1005:54: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationUIAllow
                                                     ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:1007:53: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationUIFail
                                                    ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:1009:53: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationUISkip
                                                    ^
In file included from /private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.c:6:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:124:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:65:
/System/Library/Frameworks/Security.framework/Headers/SecPolicy.h:91:60: error: expected ';' after top level declarator
extern const CFStringRef kSecPolicyApplePayIssuerEncryption
                                                           ^
In file included from /private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.c:6:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:124:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:87:
/System/Library/Frameworks/Security.framework/Headers/CMSEncoder.h:77:5: error: expected function body after function declarator
    __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_NA);
    ^
/usr/local/include/Availability.h:163:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:36:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_11
^
In file included from /private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.c:6:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:124:
In file included from /System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:91:
/System/Library/Frameworks/Security.framework/Headers/SecureTransport.h:1105:2: error: expected function body after function declarator
        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_2, __MAC_10_11, __IPHONE_5_0, __IPHONE_9_0);
        ^
/usr/local/include/Availability.h:165:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep
                                                    ^
<scratch space>:25:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_2_DEP__MAC_10_11
^
/private/var/folders/1d/5tqxnt315jjgrlrtqmj02l7m0000gn/T/python-build.20160117131021.56679/Python-3.5.1/Modules/_scproxy.c:74:10: warning: comparison of address of 'kSCPropNetProxiesExcludeSimpleHostnames' not equal to a null pointer is always true [-Wtautological-pointer-compare]
    if (&kSCPropNetProxiesExcludeSimpleHostnames != NULL) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCSchemaDefinitions.h:2153:49: note: expanded from macro 'kSCPropNetProxiesExcludeSimpleHostnames'
#define kSCPropNetProxiesExcludeSimpleHostnames kSCPropNetProxiesExcludeSimpleHostnames
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 8 errors generated.

Python build finished successfully!
The necessary bits to build these optional modules were not found:
ossaudiodev           spwd                                     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_scproxy                                                       
```

**Comment by yyuu** [comment]
Isn't there any guy encountered similar to this? Basically this could be a kind of build issue of CPython itself and could not be a problem in pyenv, though.

**Comment by oplatek** [comment]
@yyuu thanks. I think you are absolutely right. Any help is still greatly appreciated, but I do not think it is closely related to pyenv. Feel free to close the issue.

**Comment by jakirkham** [comment]
So, this is some library that is built for Mac specifically. I saw this issue also when installing 3.5.1 on 10.11. It may very well be that something changed in 10.11 that CPython has not yet accounted for. I don't see any issues raised upstream, but that may be the place to start. ( http://bugs.python.org/ )

**Comment by yyuu** [comment]
It'd be better to continue on BTS of CPython.
