### ISSUE TITLE
 pip install numpy not work in pyenv install python 2.7.8

### ISSUE THREAD

**Issue by shixudongleo** [yyuu/pyenv#523]
I have problem with pip installed numpy  in pyenv installed python2.

Details:
System: Ubuntu 14.04
Python: pyenv install 2.7.8
Python Env: pyenv virtualenv 2.7.8 test_env
Numpy: pip install numpy

The error is following:
```
$ python 
Python 2.7.8 (default, Jan  7 2016, 17:45:25) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shixd/.pyenv/versions/test_env/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/shixd/.pyenv/versions/test_env/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/shixd/.pyenv/versions/test_env/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/shixd/.pyenv/versions/test_env/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/shixd/.pyenv/versions/test_env/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /home/shixd/.pyenv/versions/test_env/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_AsUnicodeEscapeString
```

I have found out that when pip was installing numpy, it only took 3-5 seconds, so I think pip is using pre-built numpy. 

I solve the problem by manually install numpy with ```python setup.py install```. 
Why does pip  not work in my case? I don't have this problem before. (I am new in using pyenv)
How to make pip work then?

**Comment by yyuu** [comment]
Build problem with specific package isn't an issue of pyenv.
