### ISSUE TITLE
pyenv with python 2.7.11 import error

### ISSUE THREAD

**Issue by pc10201** [yyuu/pyenv#561]
My vps system is ubuntu 14.04 with python 2.7.6

when I use virtualenv(without pyenv) and django and uwsgi is OK.

But when I use virtualenv with pyenv like this

```
pyenv install 2.7.11
virtualenv -p ~/.pyenv/versions/2.7.11/bin/python  venv
```

It tell me

```
Traceback (most recent call last):
  File "example/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/home/wwwroot/www.example.com/web/example/venv/lib/python2.7/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/home/wwwroot/www.example.com/web/example/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 10, in <module>
    from django import http
  File "/home/wwwroot/www.example.com/web/example/venv/lib/python2.7/site-packages/django/http/__init__.py", line 2, in <module>
    from django.http.request import (
  File "/home/wwwroot/www.example.com/web/example/venv/lib/python2.7/site-packages/django/http/request.py", line 10, in <module>
    from django.core import signing
  File "/home/wwwroot/www.example.com/web/example/venv/lib/python2.7/site-packages/django/core/signing.py", line 48, in <module>
    from django.utils.crypto import constant_time_compare, salted_hmac
  File "/home/wwwroot/www.example.com/web/example/venv/lib/python2.7/site-packages/django/utils/crypto.py", line 8, in <module>
    import hmac
  File "/root/.pyenv/versions/2.7.11/lib/python2.7/hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
```

**Comment by yyuu** [comment]
Found similar issues with googling.

http://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest
http://stackoverflow.com/questions/24853027/django-importerror-cannot-import-name-compare-digest

I guess this could be a kind of `virtualenv` issue. I'd recommend you to install `virtualenv` into 2.7.11 just after `pyenv install 2.7.11` to make sure `virtualenv` installed inside pyenv is invoked.

**Comment by ashwoods** [comment]
I get the same error when using 2.7.11 without virtualenv.

**Comment by yyuu** [comment]
library issue with virtualenv isn't a pyenv issue.
