### ISSUE TITLE
Unable to find sqlite3 when using jupyter notebook

### ISSUE THREAD

**Issue by twmht** [yyuu/pyenv#624]
hi,

I have installed libsqlite3-dev and sqlite3

`sudo apt-get install libsqlite3-dev sqlite3`

and use the pyenv-virtualenv

`pyenv virtualenv 2.7.11 rnn`

and install the following package

```
appnope==0.1.0
backports.ssl-match-hostname==3.4.0.2
certifi==2015.9.6.2
decorator==4.0.2
funcsigs==0.4
functools32==3.2.3.post2
gnureadline==6.3.3
ipykernel==4.0.3
ipython==4.0.0
ipython-genutils==0.1.0
ipywidgets==4.0.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.0.0
jupyter-console==4.0.2
jupyter-core==4.0.6
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.7.1
mock==1.3.0
nbconvert==4.0.0
nbformat==4.0.0
nltk==3.0.5
nose==1.3.7
notebook==4.0.4
numpy==1.9.2
path.py==8.1.1
pbr==1.8.0
pexpect==3.3
pickleshare==0.5
ptyprocess==0.5
Pygments==2.0.2
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.4
pyzmq==14.7.0
qtconsole==4.0.1
scipy==0.16.0
simplegeneric==0.8.1
six==1.9.0
terminado==0.5
Theano==0.7.0
tornado==4.2.1
traitlets==4.0.0
wheel==0.26.0
```

but with

`jupyter notebook`

it shows

```
(rnn) alec@kuo--Aspire-G6-710:~/rnn-tutorial-rnnlm$ jupyter notebook
Traceback (most recent call last):
  File "/home/alec/.pyenv/versions/rnn/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/alec/.pyenv/versions/2.7.11/envs/rnn/lib/python2.7/site-packages/notebook/notebookapp.py", line 63, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/home/alec/.pyenv/versions/2.7.11/envs/rnn/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 7, in <module>
    import sqlite3
  File "/home/alec/.pyenv/versions/2.7.11/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/home/alec/.pyenv/versions/2.7.11/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
```

Any idea about this issue?

Thank you!

**Comment by eywalker** [comment]
I ran into the same issue and it turns out that this happens if you have compiled the Python binary *before* you installed `libsqlite3-dev`. Solution is quite simple: just uninstall the Python and reinstall it.

```bash
$ pyenv uninstall 2.7.11
pyenv: remove /home/eywalker/.pyenv/versions/2.7.11? y
$ pyenv install 2.7.11
```

After this `jupyter notebook` should run without complaining about `sqlite3`.

**Comment by twmht** [comment]
@eywalker , i tried your solution before, but it did not work for me.

I reinstall python with `--enable-shared` flags and it works.

`env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 2.7.11`

**Comment by peterHeuz** [comment]
Is there a way to install it not system-wide? 

I do not have sudo on my system and the admin wants to keep it clean.
