### ISSUE TITLE
Invalid syntax for unicode

### ISSUE THREAD

**Issue by chrisspen** [yyuu/pyenv#738]
I'm using Tox to test code several different Python environments, and the initialization of the virtualenv is failing for pip 8.1.2 with the error:

    New python executable in /myproject/.tox/py32-django18/bin/python3.2
    Also creating executable in /myproject/.tox/py32-django18/bin/python
    Installing setuptools, pip, wheel...
      Complete output from command /home/chris/git/djan...ango18/bin/python3.2 - setuptools pip wheel:
      /usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:80: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
    Traceback (most recent call last):
      File "<stdin>", line 7, in <module>
      File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
      File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
      File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
      File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/utils/ui.py", line 15, in <module>
      File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/progress/bar.py", line 48
        empty_fill = u'\u2219'
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
    ...Installing setuptools, pip, wheel...done.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2327, in <module>
        main()
      File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main
        symlink=options.symlink)
      File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 944, in create_environment
        download=download,
      File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 900, in install_wheel
        call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
      File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 795, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /home/chris/git/djan...ango18/bin/python3.2 - setuptools pip wheel failed with error code 1
    Running virtualenv with interpreter /usr/bin/python3.2

**Comment by joshfriend** [comment]
[`pip` 8.x and up does not support python 3.2](https://pip.pypa.io/en/stable/news/). It also says so in the error message you pasted above:

```
UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
```

You will need to do some configuring to Tox so that it stops trying to install an incompatible version of `pip`.
