### ISSUE TITLE
pip install pyenv fails on OSX

### ISSUE THREAD

**Issue by frgtn** [yyuu/pyenv#764]
pip install fails to install on OSX both on python 2.7.12 and python 3.5.2 (pip install and pip3 install)

Python 2:
```
$ pip install pyenv
Collecting pyenv
  Downloading pyenv-20150113.1.tar.gz
Building wheels for collected packages: pyenv
  Running setup.py bdist_wheel for pyenv ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-build-BxfZRo/pyenv/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/tmpjzhB1gpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.11-x86_64/wheel
  running install
  Cloning into '/Users/<user>/.pyenv'...
  Cloning into '/Users/<user>/.pyenv/plugins/pyenv-doctor'...
  Cloning into '/Users/<user>/.pyenv/plugins/pyenv-installer'...
  Cloning into '/Users/<user>/.pyenv/plugins/pyenv-pip-rehash'...
  Cloning into '/Users/<user>/.pyenv/plugins/pyenv-update'...
  Cloning into '/Users/<user>/.pyenv/plugins/pyenv-virtualenv'...
  Cloning into '/Users/<user>/.pyenv/plugins/pyenv-which-ext'...

  WARNING: seems you still have not added 'pyenv' to the load path.

  # Load pyenv automatically by adding
  # the following to your profile:

  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-build-BxfZRo/pyenv/setup.py", line 33, in <module>
      cmdclass=dict(install=PyenvInstall),
    File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 364, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.macosx-10.11-x86_64/wheel/pyenv-20150113.1-py2.7.egg-info but not found

  ----------------------------------------
  Failed building wheel for pyenv
  Running setup.py clean for pyenv
Failed to build pyenv
Installing collected packages: pyenv
  Running setup.py install for pyenv ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-build-BxfZRo/pyenv/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-1nGV5T-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-build-BxfZRo/pyenv/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-1nGV5T-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/z9/wg6pkrvs1l9c5vq01vfzsy4w0000gn/T/pip-build-BxfZRo/pyenv/
```

It would be nice to be able to pip-install pyenv and not rely on brew, git-cloning or system package managers.

**Comment by joshfriend** [comment]
https://github.com/yyuu/pyenv/issues/387#issuecomment-261269695
