### ISSUE TITLE
pyenv on CentOS 6

### ISSUE THREAD

**Issue by johnseekins** [yyuu/pyenv#785]
Having a strange problem with compiling python 2.7 on CentOS 6:

```
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Traceback (most recent call last):
  File "get-pip.py", line 20061, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/scratch/jenkins/workspace/BuildRPM/Slaves/ctdevbuild01/jenkins-BuildRPM-Slaves=ctdevbuild01-162/src/tmp/tmpIeMNBr/pip.zip/pip/__init__.py", line 28, in <module>
  File "/scratch/jenkins/workspace/BuildRPM/Slaves/ctdevbuild01/jenkins-BuildRPM-Slaves=ctdevbuild01-162/src/tmp/tmpIeMNBr/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/scratch/jenkins/workspace/BuildRPM/Slaves/ctdevbuild01/jenkins-BuildRPM-Slaves=ctdevbuild01-162/src/tmp/tmpIeMNBr/pip.zip/pip/download.py", line 36, in <module>
  File "/scratch/jenkins/workspace/BuildRPM/Slaves/ctdevbuild01/jenkins-BuildRPM-Slaves=ctdevbuild01-162/src/tmp/tmpIeMNBr/pip.zip/pip/utils/glibc.py", line 4, in <module>
  File "/scratch/jenkins/workspace/BuildRPM/Slaves/ctdevbuild01/jenkins-BuildRPM-Slaves=ctdevbuild01-162/src/versions/2.7.9/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
error: failed to install pip via get-pip.py
```

Looking further up the build log, I see this:
```
tmp/python-build.20161221121924.1030/Python-2.7.9/Modules/_ctypes/libffi/configure
building dbm using gdbm
Failed to configure _ctypes module
```

Interestingly, I also see this early in the build:
```
building '_ctypes_test' extension
creating build/temp.linux-x86_64-2.7/scratch/jenkins/workspace/BuildRPM/Slaves/ctdevbuild01/jenkins-BuildRPM-Slaves=ctdevbuild01-162/src/tmp/python-build.20161221121924.1030/Python-2.7.9/Modules/_ctypes
```

It seems like the ctypes extension is getting set to build with a _test suffix. Which is super weird.

Any idea what might cause this?

**Comment by johnseekins** [comment]
Interestingly, adding `--with-system-ffi` and `--with-system-expat` seems to circumvent this.

**Comment by yyuu** [comment]
ctypes / libffi issue. pyenv is not doing anything for it
