### ISSUE TITLE
Cannot install Twisted into pyenv venv via pip

### ISSUE THREAD

**Issue by ciarancourtney** [yyuu/pyenv#799]
To recreate:

    ~/.pyenv/versions/3.6.0/bin/python -m venv ve/
    ve/bin/pip install Twisted

output:

```
    Skipping link https://pypi.python.org/packages/fc/7f/6c81174017a0d4cb1296cdecc196b9be38fa399c6c65e84f0979456b649c/Twisted-15.2.0.win-amd64-py2.7.msi#md5=fd42c7c9d99391b6f8d84a9fc3070124 (from https://pypi.python.org/simple/twisted/); unsupported archive format: .msi
  Could not find a version that satisfies the requirement Twisted (from versions: )
Cleaning up...
No matching distribution found for Twisted
Exception information:
Traceback (most recent call last):
  File "/opt/aem/master/ve/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/aem/master/ve/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/opt/aem/master/ve/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/aem/master/ve/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/opt/aem/master/ve/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/opt/aem/master/ve/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for Twisted
```

Problem may be related to this issue http://stackoverflow.com/questions/30763614/installing-twisted-through-pip-broken-on-one-server

**Comment by yyuu** [comment]
Obviously non pyenv issue

**Comment by ciarancourtney** [comment]
FYI installing libbz2-dev before building python3.6 resolved this for me
