### ISSUE TITLE
python 2.4.3 error build/virtualenv/setup.py, line 51, with open(os.path.join(here, *paths)) as f:

### ISSUE THREAD

**Issue by nelaaro** [yyuu/pyenv#838]
Hi I am not sure if this belongs here in pyenv or with https://github.com/yyuu/pyenv-virtualenv
```
$ pyenv virtualenv 2.4.3 python243
Downloading/unpacking virtualenv
  Downloading virtualenv-15.1.0.tar.gz (1.9Mb): 1.9Mb downloaded
  Running setup.py egg_info for package virtualenv
    Traceback (most recent call last):
      File "<string>", line 14, in ?
      File "/home/aaron/projects/ECN/build/virtualenv/setup.py", line 51
        with open(os.path.join(here, *paths)) as f:
                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in ?

  File "/home/aaron/projects/ECN/build/virtualenv/setup.py", line 51

    with open(os.path.join(here, *paths)) as f:

            ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in build/virtualenv
Storing complete log in /home/aaron/.pip/pip.log
```
```
$ pyenv install 2.4.3 
Downloading Python-2.4.3.tgz...
-> https://www.python.org/ftp/python/2.4.3/Python-2.4.3.tgz
Installing Python-2.4.3...
patching file setup.py
Hunk #2 succeeded at 239 with fuzz 2 (offset -4 lines).
patching file configure
Hunk #1 succeeded at 20576 (offset -222 lines).
patching file configure.in
Hunk #1 succeeded at 3147 (offset 75 lines).
Installed Python-2.4.3 to /home/aaron/.pyenv/versions/2.4.3

Downloading setuptools-1.4.2.tar.gz...
-> https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz
Installing setuptools-1.4.2...
Installed setuptools-1.4.2 to /home/aaron/.pyenv/versions/2.4.3

Downloading pip-1.1.tar.gz...
-> https://pypi.python.org/packages/source/p/pip/pip-1.1.tar.gz
Installing pip-1.1...
Installed pip-1.1 to /home/aaron/.pyenv/versions/2.4.3
```

aaron@aaron-ubunix: ~/projects/ECN 
$ pyenv versions
* system (set by /home/aaron/.pyenv/version)
  2.4.3
  2.7
  2.7.5
  2.7.5/envs/options_checks
  2.7.5/envs/sip_options_check
  options_checks
  sip_options_check

cat /home/aaron/.pip/pip.log
```
------------------------------------------------------------
/home/aaron/.pyenv/versions/2.4.3/bin/pip run on Sun Feb 19 11:07:36 2017
Downloading/unpacking virtualenv

  Running setup.py egg_info for package virtualenv

    Traceback (most recent call last):

      File "<string>", line 14, in ?

      File "/home/aaron/projects/ECN/build/virtualenv/setup.py", line 51

        with open(os.path.join(here, *paths)) as f:

                ^

    SyntaxError: invalid syntax

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in ?

  File "/home/aaron/projects/ECN/build/virtualenv/setup.py", line 51

    with open(os.path.join(here, *paths)) as f:

            ^

SyntaxError: invalid syntax

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/aaron/projects/ECN/build/virtualenv

Exception information:
Traceback (most recent call last):
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/__init__.py", line 254, in call_subprocess
    raise InstallationError(
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/aaron/projects/ECN/build/virtualenv
```

after updating the following lines from
```
def read_file(*paths):
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, *paths)) as f:
        return f.read()
```

to 
```
 49 def read_file(*paths):
 50     here = os.path.dirname(os.path.abspath(__file__))
 51     f = open(os.path.join(here, *paths))
 52     try:
 53         for line in f:
 54             return line
 55     except Exception, err:
 56         msg = "failed to read hostname: %s" % str(err)
 57         print msg
 58         f.close()
 59 
 60     f.close()
```

It now outputs with a helpful error message. 
```
$ pyenv virtualenv -f 2.4.3 python243
Downloading/unpacking virtualenv
  Running setup.py egg_info for package virtualenv
    virtualenv requires Python 2.6 or higher.
    Complete output from command python setup.py egg_info:
    virtualenv requires Python 2.6 or higher.

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/aaron/projects/ECN/build/virtualenv
Storing complete log in /home/aaron/.pip/pip.log
```

$ cat /home/aaron/.pip/pip.log 
```
------------------------------------------------------------
/home/aaron/.pyenv/versions/2.4.3/bin/pip run on Sun Feb 19 12:03:37 2017
Downloading/unpacking virtualenv

  Running setup.py egg_info for package virtualenv

    virtualenv requires Python 2.6 or higher.

    Complete output from command python setup.py egg_info:

    virtualenv requires Python 2.6 or higher.

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/aaron/projects/ECN/build/virtualenv

Exception information:
Traceback (most recent call last):
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg/pip/__init__.py", line 254, in call_subprocess
    raise InstallationError(
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/aaron/projects/ECN/build/virtualenv
```
Which means that pip & virtualenv no longer support 2.4 line of python in the current code.

**Comment by nelaaro** [comment]
Solution:

Install that which works for the 2.4 line of python
https://virtualenv.pypa.io/en/latest/changes/#id46.
https://pypi.python.org/pypi/pip/1.1

I guess I will need to double check every pip package version for installation into 2.4
```
$ pyenv global 2.4.3

$ pip install pip==1.1
Requirement already satisfied (use --upgrade to upgrade): pip==1.1 in /home/aaron/.pyenv/versions/2.4.3/lib/python2.4/site-packages/pip-1.1-py2.4.egg
Cleaning up...

pip install virtualenv==1.7.2
Downloading/unpacking virtualenv==1.7.2
  Downloading virtualenv-1.7.2.tar.gz (2.2Mb): 2.2Mb downloaded
  Running setup.py egg_info for package virtualenv
    warning: no previously-included files matching '*' found under directory 'docs/_templates'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Installing collected packages: virtualenv
  Running setup.py install for virtualenv
    warning: no previously-included files matching '*' found under directory 'docs/_templates'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    Installing virtualenv script to /home/aaron/.pyenv/versions/2.4.3/bin
    Installing virtualenv-2.4 script to /home/aaron/.pyenv/versions/2.4.3/bin
Successfully installed virtualenv
Cleaning up...

$ pyenv virtualenv 2.4.3 python243
New python executable in /home/aaron/.pyenv/versions/2.4.3/envs/python243/bin/python2.4
Also creating executable in /home/aaron/.pyenv/versions/2.4.3/envs/python243/bin/python
Installing setuptools.............done.
Installing pip...............done.
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Unknown option: -s
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
error: failed to install pip via get-pip.py

pyenv virtualenv 2.4.3 python243
pyenv-virtualenv: `/home/aaron/.pyenv/versions/python243' already exists.

```

**Comment by yyuu** [comment]
As you know, the latest virtualenv does not support 2.4 anymore. You need to install older version of it mnually.

pyenv-virtualenv will try to install the latest version from pypi by default. If you need to use olfer version, please specify the version in VIRTUALENV_VERSION.

https://github.com/yyuu/pyenv-virtualenv/blob/master/bin/pyenv-virtualenv#L434
